/*UTILIZADO PARA TESTES*/
DROP DATABASE IF EXISTS BAR_PETISCARIA_ARV_DATABASE;

/*CRIAR A DATABASE DO BAR*/
CREATE DATABASE IF NOT EXISTS BAR_PETISCARIA_ARV_DATABASE;
USE BAR_PETISCARIA_ARV_DATABASE;

/*TABELA GUARDA OS DEPARTAMENTOS EXISTENTES NA EMPRESA */
CREATE TABLE IF NOT EXISTS DEPARTAMENTO(
     ID_DEPARTAMENTO INT PRIMARY KEY AUTO_INCREMENT,
     NOME VARCHAR(50) NOT NULL,
	 DESCRICAO VARCHAR (100) NOT NULL
     );
     
/*TABELA GUARDA DADOS DOS FUNCIONARIOS */
CREATE TABLE IF NOT EXISTS FUNCIONARIO(
     ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
     NOME VARCHAR(100) NOT NULL,
	 DATA_NASCIMENTO DATE NOT NULL,
     SEXO ENUM('M','F') NOT NULL,
     CPF VARCHAR(15) UNIQUE,
     
     ID_DEPARTAMENTO INT, 
     
     FOREIGN KEY (ID_DEPARTAMENTO)
	 REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
	 );
     
/*TABELA GUARDA DADOS DOS CLIENTES DA EMPRESA*/
CREATE TABLE IF NOT EXISTS CLIENTE(
     ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
     NOME VARCHAR(100) NOT NULL,
	 SOBRENOME VARCHAR(100) NOT NULL,
	 CPF VARCHAR(11) UNIQUE,
	 RG VARCHAR(15) NOT NULL,
	 DATA_NASCIMENTO DATE NOT NULL,
	 DATA_CADASTRO DATE NOT NULL, 
     SEXO ENUM('M','F') NOT NULL    
	 );

/*TABELA GUARDA CONTATOS DE CLIENTES E FUNCIONÁRIOS*/	  
CREATE TABLE IF NOT EXISTS CONTATO(
     ID_CONTATO INT PRIMARY KEY AUTO_INCREMENT,
     TELEFONE VARCHAR(15) UNIQUE,
	 CELULAR VARCHAR(15) UNIQUE,
	 EMAIL VARCHAR(100) UNIQUE,
	 INSTAGRAM VARCHAR(50)UNIQUE,
	 ID_CLIENTE INT UNIQUE,
     ID_FUNCIONARIO INT UNIQUE,
	 
	 FOREIGN KEY(ID_CLIENTE)
	 REFERENCES CLIENTE(ID_CLIENTE),
	 
	 FOREIGN KEY (ID_FUNCIONARIO)
	 REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
	 );
     
/*TABELA GUARDA O ENDERECO DE CLIENTES E FUNCIONARIO*/
CREATE TABLE IF NOT EXISTS ENDERECO(
     ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
     RUA VARCHAR(30) NOT NULL,
     BAIRRO VARCHAR(30) NOT NULL,
     CIDADE VARCHAR(30) NOT NULL,
     ESTADO VARCHAR(30) NOT NULL,
     ID_FUNCIONARIO INT UNIQUE,
	 ID_CLIENTE INT,
	 
	 FOREIGN KEY(ID_FUNCIONARIO)
	 REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
	 
	 FOREIGN KEY(ID_CLIENTE)
	 REFERENCES CLIENTE(ID_CLIENTE)
	 );	

/*TABELA GUARDA AS BATIDAS DE PONTO DOS FUNCIONARIOS*/
CREATE TABLE IF NOT EXISTS LISTA_PONTO(
     ID_PONTO INT PRIMARY KEY AUTO_INCREMENT,
     HORAS TIME(6) NOT NULL,
	 DATA DATE NOT NULL,
	 ID_FUNCIONARIO INT,
	 
	 FOREIGN KEY(ID_FUNCIONARIO)
	 REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
     );
     
/*TABELA GUARDA OS PEDIDOS PARA CONSUMO LOCAL E ENTREGA*/
CREATE TABLE IF NOT EXISTS PEDIDO(
	ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT, 
    VALOR_TOTAL FLOAT NOT NULL, 
    QUANT_ITENS INT NOT NULL, 
    MESA INT, 
	DATA DATE NOT NULL, 
    HORA TIME NOT NULL, 
    STATUS ENUM('M','F') NOT NULL, 
    
    ID_CLIENTE INT, 
    ID_FUNCIONARIO INT, 
    
    FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(ID_CLIENTE),
     
    FOREIGN KEY(ID_FUNCIONARIO)
	REFERENCES FUNCIONARIO(ID_FUNCIONARIO) 
);

/*TABELA GUARDA AS INFORMAÇÕES DAS MOTOS DE ENTREGA*/
CREATE TABLE IF NOT EXISTS MOTO(
	ID_MOTO INT PRIMARY KEY AUTO_INCREMENT, 
    PLACA VARCHAR(15) NOT NULL, 
    RENAVAN VARCHAR(30) NOT NULL, 
    ANO_FABRICACAO YEAR NOT NULL, 
    DATA_COMPRA DATE NOT NULL
);

/*TABELA GUARDA AS INFORMAÇÕESD E ENTREGA*/
CREATE TABLE IF NOT EXISTS ENTREGA(
	ID_ENTREGA INT PRIMARY KEY AUTO_INCREMENT, 
    ROTA TEXT, 

    END_RETIRADA INT, 
    END_ENTREGA INT,
    
    ID_FUNCIONARIO INT, 
    ID_PEDIDO INT, 
    ID_MOTO INT, 
    
    FOREIGN KEY(ID_FUNCIONARIO)
	REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
    
    FOREIGN KEY(ID_PEDIDO)
	REFERENCES PEDIDO(ID_PEDIDO),
    
    FOREIGN KEY(ID_MOTO)
	REFERENCES MOTO(ID_MOTO)
);

/*TABELA GUARDA AS INFORMAÇÕES DE PAGAMENTO*/
CREATE TABLE IF NOT EXISTS PAGAMENTO(
	ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT, 
    TIPO_PAGAMENTO ENUM('CREDITO','DEBITO', 'DINHEIRO', 'PIX') NOT NULL, 
    VALOR FLOAT, 
    
    ID_PEDIDO INT, 
    
    FOREIGN KEY(ID_PEDIDO)
	REFERENCES PEDIDO(ID_PEDIDO)
);



/*TABELA GUARDA AS QUANTIDADES DE MATERIA-PRIMA EM ESTOQUE*/
CREATE TABLE IF NOT EXISTS MATERIA_PRIMA(
	ID_MATERIA_PRIMA INT PRIMARY KEY AUTO_INCREMENT, 
    NOME INT NOT NULL, 
    DESCRICAO VARCHAR(50), 
    QUANTIDADE FLOAT NOT NULL,
    VALOR_MEDIO FLOAT NOT NULL
);

/*TABELA GUARDA OS ITENS NO MENU*/
CREATE TABLE IF NOT EXISTS ITEM_MENU(
	ID_ITEM_MENU INT PRIMARY KEY AUTO_INCREMENT, 
    NOME VARCHAR(50) NOT NULL, 
    DESCRICAO VARCHAR(100), 
    CAMINHO_IMAGEM VARCHAR(150)
);

/*TABELA GUARDA A LISTA DE PRODUTOS DO PEDIDO*/
CREATE TABLE IF NOT EXISTS LISTA_PRODUTOS_PEDIDO(
	ID_LISTA_PRODUTOS_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
	ID_PEDIDO INT, 
    ID_ITEM_MENU INT,
    
    QUANTIDADE INT,
    VALOR FLOAT, 
    
    FOREIGN KEY(ID_PEDIDO)
	REFERENCES PEDIDO(ID_PEDIDO),
    
    FOREIGN KEY(ID_ITEM_MENU)
	REFERENCES ITEM_MENU(ID_ITEM_MENU)
);

/*TABELA GUARDA AS CATEGORIAS DE ITENS DO MENU*/
CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL, 
    DESCRICAO VARCHAR(100)
);

/*TABELA ONDE SE GUARDA AS ORDENS DE COMPRA*/
CREATE TABLE IF NOT EXISTS ORDEM_COMPRA(
	ID_ORDEM_COMPRA INT PRIMARY KEY AUTO_INCREMENT, 
    OBSERVACAO VARCHAR(100), 
    QUANTIDADE_ITENS INT NOT NULL,
    VALOT_TOTAL FLOAT, 
    TIPO_PAGAMENTO ENUM('CREDITO','DEBITO', 'DINHEIRO', 'PIX') NOT NULL  
);


/*TABELA GUARDA AS INFORMACOES DOS FORNECEDORES*/
CREATE TABLE IF NOT EXISTS FORNECEDOR(
	ID_FORNECEDOR INT PRIMARY KEY AUTO_INCREMENT, 
    RAZAO_SOCIAL VARCHAR(50) NOT NULL, 
    NOME_FANTANSIA VARCHAR(50) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL, 
    INSC_ESTADUAL VARCHAR(20) NOT NULL
);

/*TABELA GUARDA A LISTA DE PRODUTOS EM CADA COMPRA*/
CREATE TABLE IF NOT EXISTS LISTA_PRODUTOS_COMPRA(
	ID_ORDEM_COMPRA INT,
    ID_MATERIA_PRIMA INT, 
    QUANTIDADE INT NOT NULL, 
    VALOR FLOAT NOT NULL, 
    
    FOREIGN KEY(ID_ORDEM_COMPRA)
	REFERENCES ORDEM_COMPRA(ID_ORDEM_COMPRA),
    
    FOREIGN KEY(ID_MATERIA_PRIMA)
	REFERENCES MATERIA_PRIMA(ID_MATERIA_PRIMA)
);







     
     