/*FILE WITH SQL PROCEDURES OF BAR_PETISCARIA_ARV_DATABASE*/

/*PROCEDURE SELECIONA TODOS OS CLIENTES COM ENDERECO*/
DELIMITER //
CREATE PROCEDURE SELECT_CLIENTE_COM_ENDERECO ()
BEGIN
	SELECT CLIENTE.ID_CLIENTE, CLIENTE.NOME, CLIENTE.SOBRENOME, ENDERECO.ENDERECO, ENDERECO.NUMERO,
	BAIRRO.BAIRRO, CIDADE.CIDADE, ESTADO.ESTADO, PAIS.PAIS
	FROM CLIENTE
	INNER JOIN ENDERECO ON CLIENTE.ID_CLIENTE = ENDERECO.ID_CLIENTE
	INNER JOIN BAIRRO ON BAIRRO.ID_BAIRRO = ENDERECO.ID_BAIRRO
	INNER JOIN CIDADE ON CIDADE.ID_CIDADE = ENDERECO.ID_CIDADE
	INNER JOIN ESTADO ON ESTADO.ID_ESTADO = ENDERECO.ID_ESTADO
	INNER JOIN PAIS ON PAIS.ID_PAIS = ENDERECO.ID_PAIS;
 END //
 DELIMITER ;

/*PROCEDURE SELECIONA CLIENTES EM BAIRRO*/
DELIMITER //
CREATE PROCEDURE SELECT_CLIENTE_BY_BAIRRO ()
BEGIN
	SELECT CLIENTE.ID_CLIENTE, CLIENTE.NOME, CLIENTE.SOBRENOME, ENDERECO.ENDERECO, ENDERECO.NUMERO,
	BAIRRO.BAIRRO, CIDADE.CIDADE, ESTADO.ESTADO, PAIS.PAIS
	FROM CLIENTE
	INNER JOIN ENDERECO ON CLIENTE.ID_CLIENTE = ENDERECO.ID_CLIENTE
	INNER JOIN BAIRRO ON BAIRRO.ID_BAIRRO = ENDERECO.ID_BAIRRO
	INNER JOIN CIDADE ON CIDADE.ID_CIDADE = ENDERECO.ID_CIDADE
	INNER JOIN ESTADO ON ESTADO.ID_ESTADO = ENDERECO.ID_ESTADO
	INNER JOIN PAIS ON PAIS.ID_PAIS = ENDERECO.ID_PAIS;
 END //
 DELIMITER ;

CALL SELECT_CLIENTE_COM_ENDERECO;
/*PROCEDURE SELECIONA CLIENTES EM CIDADE*/

/*PROCEDURE SELECIONA CLIENTES EM ESTADO*/

/*PROCEDURE SELECIONA CLIENTES EM PAIS*/

/*PROCEDURE SELECIONA TODOS OS CLIENTES COM CONTATO*/
