
USE BAR_PETISCARIA_ARV_DATABASE;
/*FILE WITH SQL VIEWS OF BAR_PETISCARIA_ARV_DATABASE*/

/*VIEW SELECIONA OS CLIENTES COM SUAS INFORMAÇÕES DE ENDERECO*/
DROP VIEW IF EXISTS VIEW_SELECT_CLIENTE_COM_ENDERECO;
CREATE VIEW  VIEW_SELECT_CLIENTE_COM_ENDERECO AS
	SELECT CLIENTE.ID_CLIENTE, CLIENTE.NOME, CLIENTE.SOBRENOME, 
			IFNULL(ENDERECO.ENDERECO, "SEM ENDERECO") AS ENDERECO,
            IFNULL(ENDERECO.NUMERO, "SEM NUMERO") AS NUMERO,
			IFNULL(BAIRRO.BAIRRO,  "SEM BAIRRO") AS BAIRRO,
            IFNULL(CIDADE.CIDADE,  "SEM CIDADE") AS CIDADE,
            IFNULL(ESTADO.ESTADO,  "SEM ESTADO") AS ESTADO,
            IFNULL(PAIS.PAIS, "SEM PAIS") AS PAIS
	FROM CLIENTE
	LEFT JOIN ENDERECO ON CLIENTE.ID_CLIENTE = ENDERECO.ID_CLIENTE
	LEFT JOIN BAIRRO ON BAIRRO.ID_BAIRRO = ENDERECO.ID_BAIRRO
	LEFT JOIN CIDADE ON CIDADE.ID_CIDADE = ENDERECO.ID_CIDADE
	LEFT JOIN ESTADO ON ESTADO.ID_ESTADO = ENDERECO.ID_ESTADO
	LEFT JOIN PAIS ON PAIS.ID_PAIS = ENDERECO.ID_PAIS;

/*VIEW SELECIONA OS CLIENTES CLIENTES COM SUAS INFORMAÇÕES DE CONTATO*/
DROP VIEW IF EXISTS VIEW_SELECT_CLIENTE_COM_CONTATOS;
CREATE VIEW VIEW_SELECT_CLIENTE_COM_CONTATOS AS
	SELECT CLIENTE.ID_CLIENTE, CLIENTE.NOME, CLIENTE.SOBRENOME, 
				IFNULL(TELEFONE.TELEFONE, "SEM TELEFONE")  AS TELEFONE, 
                IFNULL(EMAIL.EMAIL, "SEM EMAIL") AS EMAIL
	FROM CLIENTE
    LEFT JOIN TELEFONE ON CLIENTE.ID_CLIENTE = TELEFONE.ID_CLIENTE
    LEFT JOIN EMAIL ON CLIENTE.ID_CLIENTE = EMAIL.ID_CLIENTE;

/*VIEW SELECIONA OS CLIENTES COM SUAS INFORMAÇÕES DE ENDERECO*/
DROP VIEW IF EXISTS VIEW_SELECT_FUNCIONARIO_COM_ENDERECO;
CREATE VIEW  VIEW_SELECT_FUNCIONARIO_COM_ENDERECO AS
	SELECT FUNCIONARIO.ID_FUNCIONARIO, FUNCIONARIO.NOME, FUNCIONARIO.SOBRENOME, 
			IFNULL(ENDERECO.ENDERECO, "SEM ENDERECO") AS ENDERECO,
            IFNULL(ENDERECO.NUMERO, "SEM NUMERO") AS NUMERO,
			IFNULL(BAIRRO.BAIRRO,  "SEM BAIRRO") AS BAIRRO,
            IFNULL(CIDADE.CIDADE,  "SEM CIDADE") AS CIDADE,
            IFNULL(ESTADO.ESTADO,  "SEM ESTADO") AS ESTADO,
            IFNULL(PAIS.PAIS, "SEM PAIS") AS PAIS
	FROM FUNCIONARIO
	LEFT JOIN ENDERECO ON FUNCIONARIO.ID_FUNCIONARIO = ENDERECO.ID_CLIENTE
	LEFT JOIN BAIRRO ON BAIRRO.ID_BAIRRO = ENDERECO.ID_BAIRRO
	LEFT JOIN CIDADE ON CIDADE.ID_CIDADE = ENDERECO.ID_CIDADE
	LEFT JOIN ESTADO ON ESTADO.ID_ESTADO = ENDERECO.ID_ESTADO
	LEFT JOIN PAIS ON PAIS.ID_PAIS = ENDERECO.ID_PAIS;

/*VIEW SELECIONA OS FUNCIONARIOS DA EMPRESA COM SUAS INFORMAÇÕES DE CONTATO*/
DROP VIEW IF EXISTS VIEW_SELECT_FUNCIONARIO_COM_CONTATOS;
CREATE VIEW VIEW_SELECT_FUNCIONARIO_COM_CONTATOS AS
	SELECT FUNCIONARIO.ID_FUNCIONARIO, FUNCIONARIO.NOME, FUNCIONARIO.SOBRENOME, 
			IFNULL(TELEFONE.TELEFONE, "SEM TELEFONE")  AS TELEFONE, 
			IFNULL(EMAIL.EMAIL, "SEM EMAIL") AS EMAIL
	FROM FUNCIONARIO
    LEFT JOIN TELEFONE ON FUNCIONARIO.ID_FUNCIONARIO = TELEFONE.ID_FUNCIONARIO
    LEFT JOIN EMAIL ON FUNCIONARIO.ID_FUNCIONARIO = EMAIL.ID_FUNCIONARIO;

/*VIEW SELECIONA AS MOTOS DA EMPRESA*/
DROP VIEW IF EXISTS VIEW_MOTOS;
CREATE VIEW VIEW_MOTOS AS
	SELECT MOTO.ID_MOTO, MOTO.PLACA, MOTO.RENAVAN, MOTO.ANO_FABRICACAO, MOTO.DATA_COMPRA
    FROM MOTO;
    
DROP VIEW IF EXISTS VIEW_PEDIDO;
CREATE VIEW VIEW_PEDIDOS AS 
	SELECT PEDIDO.VALOR_TOTAL, PEDIDO.QUANT_ITENS, PEDIDO.MESA, PEDIDO.DATA, PEDIDO.HORA, 
    PEDIDO.STATUS, PEDIDO.ID_CLIENTE, PEDIDO.ID_FUNCIONARIO FROM PEDIDO;