

create database PROJETO_INTEGRADOR;

use PROJETO_INTEGRADOR;

CREATE TABLE CLIENTE(
     IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
     NOME VARCHAR(100) NOT NULL,
	 SOBRENOME VARCHAR(100) NOT NULL,
	 CPF VARCHAR(15) UNIQUE,
	 RG VARCHAR(15) NOT NULL,
	 DATA_NASCIMENTO DATE NOT NULL,
	 DATA_CADASTRO DATE NOT NULL, 
     SEXO ENUM('M','F') NOT NULL
	 );
	  
CREATE TABLE CONTATO(
     IDCONTATO INT PRIMARY KEY AUTO_INCREMENT,
     TELEFONE VARCHAR(15) UNIQUE,
	 CELULAR VARCHAR(15) UNIQUE,
	 EMAIL VARCHAR(50) UNIQUE
	 INSTAGRAM VACHAR(50)UNQUE,
     EMAIL VARCHAR(50) UNIQUE
	 
	 );
	 
CREATE TABLE FUNCIONARIO(
     IDFUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
     NOME VARCHAR(100) NOT NULL,
	 DATA_NASCIMENTO DATE NOT NULL,
     SEXO ENUM('M','F') NOT NULL,
     CPF VARCHAR(15) UNIQUE
	 RG VARCHAR (30) NOT NULL
	 );

CREATE TABLE ENDERECO(
     IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
     RUA VARCHAR(30) NOT NULL,
	 NUMERO INT NOT NULL,
     BAIRRO VARCHAR(30) NOT NULL,
     CIDADE VARCHAR(30) NOT NULL,
     ESTADO VARCHAR(30) NOT NULL,
	 PAIS VARCHAR (30) DEFAULT 'BRASIL'
	 CEP VARCHAR (30),
     ID_FUNCIONARIO INT UNIQUE,
	 
	 FOREIGN KEY(ID_FUNCIONARIO)
	 REFERENCES FUNCIONARIO(IDFUNCIONARIO)
	);
	
CREATE TABLE DEPARTAMENTO(
     IDDEPATAMENTO INT PRIMARY KEY AUTO_INCREMENT,
     NOME_DEP VARCHAR(50) NOT NULL,
	 DESCRICAO VARCHAR (100) NOT NULL,
     ID_FUNCIONARIO INT UNIQUE,
	 
	 FOREIGN KEY(ID_FUNCIONARIO)
	 REFERENCES FUNCIONARIO(IDFUNCIONARIO)
     );
	 
CREATE TABLE LISTA_PONTO(
     IDPONTO INT PRIMARY KEY AUTO_INCREMENT,
     HORAS TIME(6) NOT NULL,
	 DATA DATE NOT NULL
     );
	 
CREATE TABLE PEDIDO(
     IDPEDIDO INT PRIMARY KEY AUTO_INCREMENT,
     VALOR_TOTAL FLOAT(10,2),
	 QUANT_ITENS INT,
	 MESA INT,
	 DATA DATE, NOT NULL,
	 HORAS TIME, NOT NULL,
	 STATUS CHAR NOT NULL
	 );
     
CREATE TABLE ENTREGA(
     IDENTREGA INT PRIMARY KEY AUTO_INCREMENT,
     ROTA VARCHAR (200) NOT NULL,
	 END_RETIRADA VARCHAR (100) NOT NULL /* ENDEREÇO DE ENTREGA VIRA DA TABELA ENDEREÇO*/
	 );
	 
CREATE TABLE MOTO(
     IDMOTO INT PRIMARY KEY AUTO_INCREMENT,
     PLACA VARCHAR (15) NOT NULL,
	 RENAVAN VARCHAR (100) NOT NULL,
	 ANO_FAB DATE NOT NULL,
	 DATA_COMPRA DATE NOT NULL
	 );
	 
CREATE TABLE PRODUTO(
     IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,	 
	 NOME VARCHAR (100) NOT NULL, 
	 DESCRICAO TEXT (300) NOT NULL, 
	 CAMINHO_IMAGEM VARCHAR (200)
	 );
	 
CREATE TABLE PAGAMENTO(
     IDPAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,	 
	 TIPO ENUM ('PIX','CC','CB','D')NOT NULL,
	 VALOR FLOAT (10,2) NOT NULL
	 );
	 
CREATE TABLE FORNECEDOR(
     IDFORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,	 
	 RAZAO VARCHAR (100)NOT NULL,
	 NOME_FANTASIA VARCHAR (100) NOT NULL
	 CNPJ VARCHAR (30) NOT NULL,
	 );
	 